import { globalSave } from './database.js';
import { utils } from './utils.js';

// Tarik semua data yang diperlukan untuk ringkasan
let invoices = JSON.parse(localStorage.getItem('f6_invoices')) || [];
let expenses = JSON.parse(localStorage.getItem('f6_expenses')) || [];
let inventory = JSON.parse(localStorage.getItem('f6_inventory')) || [];
let profile = JSON.parse(localStorage.getItem('f6_profile')) || { name: '', addr: '', bank: '' };

/**
 * Render utama untuk Dashboard
 */
export function renderDashboard() {
    // 1. Paparkan Tarikh Hari Ini (Guna utils)
    const dateDisplay = document.getElementById('current-date-display');
    if (dateDisplay) {
        dateDisplay.innerText = utils.formatDate(new Date());
    }

    // 2. Kira Statistik Kewangan
    const totalRevenue = invoices
        .filter(inv => inv.status === 'Paid')
        .reduce((sum, inv) => sum + parseFloat(inv.total), 0);

    const totalExpense = expenses
        .reduce((sum, exp) => sum + parseFloat(exp.amount), 0);

    const grossMargin = totalRevenue - totalExpense;

    // 3. Update UI Statistik (Guna utils.formatRM)
    document.getElementById('dash-total-rev').innerText = utils.formatRM(totalRevenue);
    document.getElementById('dash-total-margin').innerText = utils.formatRM(grossMargin);
    document.getElementById('dash-tax-expense').innerText = utils.formatRM(totalExpense);
    document.getElementById('dash-inv-count').innerText = `${inventory.length} Jenis`;

    // 4. Update Profil Syarikat di UI
    document.getElementById('set-biz-name').value = profile.name || '';
    document.getElementById('set-biz-addr').value = profile.addr || '';
    document.getElementById('set-biz-bank').value = profile.bank || '';

    renderCalendarWidget();
}

/**
 * Logik Simpan Profil Syarikat (Auto-save on input)
 */
window.updateBizProfile = () => {
    const name = document.getElementById('set-biz-name').value;
    const addr = document.getElementById('set-biz-addr').value;
    const bank = document.getElementById('set-biz-bank').value;

    const newProfile = { name, addr, bank };
    
    // Simpan ke LocalStorage & Cloud
    globalSave({ profile: newProfile });
    localStorage.setItem('f6_profile', JSON.stringify(newProfile));
};

/**
 * Widget Kalendar / Nota Ringkas
 */
function renderCalendarWidget() {
    const container = document.getElementById('calendar-widget');
    if (!container) return;

    // Contoh data nota (Boleh disambung ke DB nanti)
    const notes = [
        { title: "Follow-up LHDN", tag: "Tax", color: "orange" },
        { title: "Restock Inventori", tag: "Stock", color: "blue" },
        { title: "Review Sales", tag: "Audit", color: "emerald" }
    ];

    container.innerHTML = notes.map(note => `
        <div class="bg-white p-6 rounded-[28px] border border-gray-100 shadow-sm hover:shadow-md transition">
            <span class="text-[8px] font-black bg-${note.color}-100 text-${note.color}-600 px-3 py-1 rounded-full uppercase mb-3 inline-block">
                ${note.tag}
            </span>
            <p class="font-bold text-gray-800 text-sm">${note.title}</p>
            <p class="text-[9px] text-gray-400 mt-2 font-medium">Auto-generated by KETICK</p>
        </div>
    `).join('');
}

window.addJob = () => {
    alert("Ciri 'Smart Notes' akan disambungkan ke Google Calendar anda tidak lama lagi!");
};
